CREATE TABLE Journal (
    time DATETIME NOT NULL PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    item TEXT NOT NULL,
    price INT NOT NULL,
    paid BOOLEAN NOT NULL
);

CREATE TABLE Drinks (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(32) NOT NULL,
    price INT NOT NULL
);

CREATE TABLE Users (
    id VARCHAR(32) NOT NULL PRIMARY KEY,
    name VARCHAR(16) NOT NULL,
    email VARCHAR(128) NOT NULL
);
